import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-100`}
      >
        <header className="flex items-center justify-center gap-3 font-semibold py-3">
          <Link href="/">Home</Link>
          <Link href="/community">Community</Link>
          <Link href="/recommended">Attendees-Recommended</Link>
          <Link href="/category">Attendees-Category</Link>
        </header>
        {children}
      </body>
    </html>
  );
}
